var sentenceList = [
    "He flew round in an instant to look his attacker square in the eye.",
    "The kid gave a long moan when the milk was spilt.",
    "The table is badly glued and made so sloppily that it tilts.",
    "We're glad that the price range is smaller than any of us expected.",
    "The grass was mown before the uncontrollable children came out to play.",
    "He hurled several stones from the bridge whilst I quickly ran for cover.",
    "Troy flicks through a yuppie magazine when he gets a chance.",
    "Thank goodness it's Friday and time to go home!",
    "Pete sat in the little boat with his bait and his fishing boots on the floor beside him waiting for the trout to bite.",
    "Who says itches are always so tempting to scratch?",
    "Actually, I'll hedge my bets and take no risks on this flutter.",
    "Alan took a ham sandwich to school.",
    "The length of her skirt caused the passers-by to glare.",
    "I'll thrash out a draft and lodge those new proposals before the next mass meeting.",
    "She'll think of an excuse why she overslept if given enough time and space.",
    "Helen picked a good spot near the water and spent the morning surfing and relaxing in the sun.",
    "Unfortunately, the bath plug is missing so you'll have to take a shower.",
    "The group asked if I wanted to come along on the barge trip.",
    "You ought to brush your teeth and wash your face before you go to bed.",
    "The earth used to be flat, but now it's a sphere ... isn't it?",
    "I wish he'd either grow a beard or shave his scruffy moustache.",
    "Melvin's cat was slowly rolling the can.",
    "Judith found the three manuscripts waiting for her on the piano.",
    "The dwarf's throne was in a huge castle encircled by a deep moat.",
    "Isn't it odd how cobwebs slowly find their way into every nook and cranny!",
    "Mr Boyd says these practical jokes have been taken much too far.",
    "I said she couldn't do it but she can.",
    "This year I shall paint this room mauve with a splotch of beige dots.",
    "It can be quite risky changing gear whilst half way up a steep hill.",
    "There'll be big trouble if you dare to touch that stretched surface.",
    "Amongst her friends at the Glebe Baths she was considered beautiful.",
    "The truth is, I wish I lived a little bit nearer to the supermarket.",
    "Don't breathe a word of this, but the topic of Jeff's speech is beginning to annoy me.",
    "This new glove and shoe display attracts more customers than ever!",
    "We'd be hard pushed for the whole squad to catch the bus to Springwood tonight.",
    "The nurse tended the fierce-looking flesh wound on Paul's scalp.",
    "Bill could have sat on the train like a zombie but chose to stand.",
    "Most of the scenes filmed on location in the Alps were breathtaking.",
    "The flag ceremony overwhelmed me and I was moved to tears.",
    "Was it the blue globe that broke when he switched on the light?",
    "Don't you think her evening gown was a trifle too garish for the occasion?",
    "He glimpsed the badge of the traffic cop out of the corner of his eye.",
    "He grabbed a towel and then answered the phone by the clock.",
    "Sharon vowed never again to sneer at tourists buying souvenir dolls.",
    "It seems as if Susan does all the floor cleaning for this frugal household.",
    "John could supply him with the latest draft of his work to proof-read.",
    "The dear old bishop was thrust into trouble with the self-absorbed mayor.",
    "I've just seen that rogue, Charles, tearing off in a hurry to his maths exam.",
    "My mother gets cross when they say 'yeah' instead of 'yes'.",
    "A squirt of this ointment will soothe the graze on your heel.",
    "Isn't it common knowledge that the kangaroo has a pouch in front?",
    "Apparently, bulldog terriers yap almost as much as chows.",
    "Surely, if you leave the record by the fire it will warp.",
    "Enjoying her freedom, Amelia went to the zoo and saw a rare giant sloth.",
    "Please, I feel too lethargic to wash up tonight.",
    "The plane flew down low over the runway, then increased speed and circled the airfield a second time.After a gaffe like that, it is futile to offer any further resistance, isn't it?",
    "The chill wind caused the twins to shiver violently in their threadbare clothes.",
    "Sharon watched the helicopter as it lifted off the deck hovered for a couple of seconds and then landed once more.",
]